version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres_student_distribution
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./Database/Init:/docker-entrypoint-initdb.d

volumes:
  pg_data: